directory: /Volumes/Archivum/Music
library: ~/.config/beets/musiclibrary.db

asciify_paths: yes
id3v23: true

import:
  move: yes
  write: yes

plugins: convert fetchart embedart lyrics lastgenre

convert:
  auto: yes
  copy_album_art: yes
  format: opus
  formats:
    opus:
      command: ffmpeg -i $source -y -acodec libopus $dest
      extension: opus

fetchart:
  cautious: true
  sources: itunes *

embedart:
  remove_art_file: true
