.local/share/powerlevel10k:
  type: archive
  refreshPeriod: 168h
  stripComponents: 1
  url: https://github.com/romkatv/powerlevel10k/archive/refs/heads/master.tar.gz

{{ if ne .chezmoi.os "darwin" }}
.config/zsh/rc.d/69-iterm.zsh:
  type: file
  exact: true
  refreshPeriod: 168h
  url: https://iterm2.com/shell_integration/zsh
{{ end }}

.local/share/zsh-autosuggestions:
  type: archive
  refreshPeriod: 168h
  stripComponents: 1
  url: https://github.com/zsh-users/zsh-autosuggestions/archive/refs/heads/master.tar.gz

.local/share/zsh-completions:
  type: archive
  refreshPeriod: 168h
  stripComponents: 1
  url: https://github.com/zsh-users/zsh-completions/archive/refs/heads/master.tar.gz

.local/share/zsh-history-substring-search:
  type: archive
  refreshPeriod: 168h
  stripComponents: 1
  url: https://github.com/zsh-users/zsh-history-substring-search/archive/refs/heads/master.tar.gz

.local/share/zsh-syntax-highlighting:
  type: archive
  refreshPeriod: 168h
  stripComponents: 1
  url: https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/heads/master.tar.gz

.local/share/nano-syntax-highlighting:
  type: archive
  refreshPeriod: 672h  # 4 weeks
  stripComponents: 1
  url: https://github.com/scopatz/nanorc/archive/refs/heads/master.tar.gz
