#!/bin/sh
# Create a temporary directory using mktemp and cd into it.
# Optionally accept a custom prefix

if [ -z "$1" ]; then
  prefix=tempdir
else
  prefix=$1
fi
tempdir="$(mktemp -d "${TMPDIR}""${prefix}"-XXXXXX)" || exit 1
cd "$tempdir" || exit 1
