#!/bin/sh
# Prunes stopped containers, unused volumes, images, and networks in Docker.
# MAY RESULT IN A MASSIVE DATA LOSS!

echo "Removing stopped containers..."
docker container prune

echo
echo "Removing unused volumes..."
docker volume prune

echo
echo "Removing unused images..."
docker image prune --all

echo
echo "Removing unused networks..."
docker network prune --all

echo
echo "Done."
