#!/usr/bin/env sh

if [ $# -eq 0 ]; then
	# Nothing supplied, using current dirname; using PWD
	_repo_name=$(basename "$PWD")
else
	_repo_name=$1
fi

# Initialize a git repo and add my remotes
if [ ! -d ".git" ]; then
	git init
fi

git remote add origin "git@github.com:kytta/$_repo_name.git"
git remote add codeberg "git@codeberg.org:kytta/$_repo_name.git"
git remote add soft "ssh://git@ky.noho.st:23231/$_repo_name"
