#!/usr/bin/env zsh

# Anonymous function to scope variables in dotfiles
() {
  # `define local variables
  local gitdir=~/Git  # Where to keep repos and plugins

  # Load all of the files in rc.d that start with <number>- and end in .zsh
  local file=
  for file in $ZDOTDIR/rc.d/<->-*.zsh(n); do
    . $file
  done
} "$@"
